version: '3.8'

services:
  fastapi:
    build: .
    container_name: rag-ocr-api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    volumes:
      # Mount rag_storage to persist extracted text
      - ./rag_storage:/app/rag_storage
      # Mount uploads directory to persist uploaded PDFs
      - ./uploads:/app/uploads
    restart: unless-stopped
    env_file:
      - .env